#!/usr/bin/env python3
"""Build a lightweight, browsable review bundle for a MANGO run tier.

Scientific outputs stay in ``artifacts/``.  This bundle uses relative symlinks
so checkpoints and model assets are not duplicated, while a JSON manifest
records both available and still-missing outputs during an incremental run.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import tempfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MARKER = ".mango_review_bundle"


def link(source: Path, destination: Path, records: list[dict], label: str) -> None:
    source = source if source.is_absolute() else ROOT / source
    item = {
        "label": label,
        "canonical_path": str(source.relative_to(ROOT)),
        "available": source.exists(),
        "review_path": None,
    }
    if source.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.symlink_to(os.path.relpath(source, destination.parent),
                               target_is_directory=source.is_dir())
        item["review_path"] = str(destination)
    records.append(item)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tier", choices=("smoke", "small", "full"), required=True)
    parser.add_argument("--report", default="artifacts/gpu/results_report.json")
    parser.add_argument("--output")
    args = parser.parse_args()

    report_path = ROOT / args.report
    if not report_path.exists():
        raise SystemExit(f"results report does not exist: {report_path}")
    report = json.loads(report_path.read_text())
    output = ROOT / (args.output or f"review/{args.tier}_artifacts")

    if output.exists() and not (output / MARKER).exists():
        # A fresh checkout can contain only the curated, tracked GitHub review
        # exports. They are explicitly preserved below, so this is a safe
        # bootstrap case; refuse every other unmarked directory.
        entries = {path.name for path in output.iterdir()}
        if entries - {"github"}:
            raise SystemExit(f"refusing to replace unmarked directory: {output}")

    output.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}.", dir=output.parent))
    records: list[dict] = []
    try:
        (staging / MARKER).write_text("generated by collect_review_artifacts.py\n")
        link(report_path, staging / "summary" / "results_report.json", records,
             "incremental results report (JSON)")
        link(ROOT / "artifacts/gpu/results_report.csv",
             staging / "summary" / "results_report.csv", records,
             "incremental results report (CSV)")
        link(ROOT / "artifacts/gpu/results_complete.json",
             staging / "summary" / "results_complete.json", records,
             "strict completion manifest")
        link(ROOT / "artifacts/gpu/preflight.json",
             staging / "summary" / "gpu_preflight.json", records,
             "GPU preflight")
        link(ROOT / "artifacts/data/sabdab2_v0.1.0/processed/records.csv",
             staging / "summary" / "processed_records.csv", records,
             "processed cohort")
        link(ROOT / "artifacts/logs/smoke_all.log",
             staging / "logs" / "smoke_all.log", records,
             "inclusive smoke log")

        rows = []
        for embedder, result in report.get("runs", {}).items():
            expected = result.get("expected_paths", {})
            run_id = expected.get("run_id") or result.get("run_id")
            base = staging / "embedders" / embedder
            if run_id:
                link(ROOT / "artifacts/runs" / run_id, base / "run", records,
                     f"{embedder} run outputs and checkpoints")
                link(ROOT / "artifacts/analysis" / run_id, base / "analysis", records,
                     f"{embedder} analysis tables")
                link(ROOT / "artifacts/designs" / run_id, base / "designs", records,
                     f"{embedder} generated designs")
            for log_name, path in expected.get("logs", {}).items():
                link(ROOT / path, base / "logs" / f"{log_name}.log", records,
                     f"{embedder} {log_name} log")
            if expected.get("embedding"):
                link(ROOT / expected["embedding"], base / "embedding_manifest.json",
                     records, f"{embedder} embedding completion manifest")
            if expected.get("weights"):
                link(ROOT / expected["weights"], base / "weights_manifest.json",
                     records, f"{embedder} pretrained weights manifest")
            rows.append((embedder, result.get("status", "unknown"), run_id or "—"))

        for path in sorted((ROOT / "artifacts/gpu").glob("*.png")):
            link(path, staging / "figures" / path.name, records, f"GPU figure {path.name}")
        for path in sorted((ROOT / "artifacts/gpu").glob("*.csv")):
            if path.name != "results_report.csv":
                link(path, staging / "figure_data" / path.name, records,
                     f"GPU figure data {path.name}")
        for path in sorted((ROOT / "artifacts/analysis/figures").glob("*.png")):
            link(path, staging / "figures" / path.name, records,
                 f"cross-model analysis figure {path.name}")
        for path in sorted((ROOT / "artifacts/analysis/figures").glob("*.csv")):
            link(path, staging / "figure_data" / path.name, records,
                 f"cross-model figure data {path.name}")

        generated = datetime.now(timezone.utc).isoformat()
        manifest = {
            "tier": args.tier,
            "generated_at": generated,
            "canonical_artifact_root": "artifacts",
            "link_policy": "relative symlinks; checkpoint bytes are not duplicated",
            "summary": report.get("summary", {}),
            "items": records,
        }
        (staging / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

        table = "\n".join(f"| {e} | {s} | `{r}` |" for e, s, r in rows)
        readme = f"""# MANGO {args.tier.title()} Artifacts

Generated: {generated}

This is a lightweight index into the canonical files under `artifacts/`.
Large checkpoints and model assets are relative symlinks rather than copies.
Open `embedders/<name>/run/training_curve.png` first for train/validation NLL,
then `eval.json`, `predictions_test.csv`, and the `analysis/metrics/` tables.

| Embedder | Current status | Run ID |
|---|---|---|
{table}

The bundle is refreshed incrementally, so missing methods during an active run
are expected. `manifest.json` records every available and missing item.
"""
        (staging / "README.md").write_text(readme)

        if output.exists():
            # The generated symlink index is replaced atomically after every
            # model, while the lightweight, tracked review exports are curated
            # incrementally. Preserve that non-generated subtree across index
            # refreshes instead of deleting already published model results.
            github_review = output / "github"
            if github_review.exists():
                shutil.copytree(github_review, staging / "github")
            shutil.rmtree(output)
        staging.rename(output)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise

    available = sum(item["available"] for item in records)
    print(f"review bundle: {available}/{len(records)} indexed items available -> {output}")


if __name__ == "__main__":
    main()
